### ISSUE TITLE
write dead line-height of icon

### ISSUE THREAD

**Issue by yangbin1994** [nobitagit/react-material-floating-button#29]
```scss
.mfb-component__icon{
  position: absolute;
  font-size: 18px;
  text-align: center;
  line-height: 56px; // $main_button_size or $child_button_size?
  width: 100%;
}
```
